### ISSUE TITLE
Ubuntu Jammy

### ISSUE THREAD

**Issue by mcyzyk** [hubick/gnome-shell-extension-zfs-status-monitor#1]
Any way this might be upgraded so it will run on Ubuntu Jammy?  With detailed installation instructions that do not require use of Firefox (which is now a Snap on Ubuntu, so cannot install Gnome Extensions)?  I would love to use this widget!

**Comment by hubick** [comment]
Luckily, I just switched back to Fedora 36 from RHEL9 and tested the extension on the newer Gnome, and it works fine, so I've just pushed a version 2 updating the compatibility declaration.

You should be able to manually install the extension by using the download option at [https://extensions.gnome.org/extension/4568/zfs-status-monitor/](https://extensions.gnome.org/extension/4568/zfs-status-monitor/), and placing the files from the zip file it gives you into a folder under your home directory at `.local/share/gnome-shell/extensions/zfs-status-monitor@chris.hubick.com/`, and then restarting or logging out/in. The Gnome "Extensions" application should hopefully offer you updates after that.
