### ISSUE TITLE
Gnome Shell Extension Manager:  "Unsupported"

### ISSUE THREAD

**Issue by mcyzyk** [hubick/gnome-shell-extension-zfs-status-monitor#2]
Trying to install in Ubuntu Jammy in Firefox.  Apparently, you can't install these extensions in Firefox because in Ubuntu the standard is to install Firefox as a Snap.  The alternative is to use the Gnome Extension Manager utility.  This I did, but get an "Unsupported" error (see attached screenshot.)  Any way to install this using the Gnome Extension Manager?

![snapshot1](https://user-images.githubusercontent.com/7024933/189684557-0bd9fcaf-bc8b-4aca-a789-a35bb20c58ad.png)

**Comment by hubick** [comment]
I'm a Fedora user. Google says Jammy is Gnome 42? This extension lists 42 as supported, so I don't have any idea why it won't install. Do you have a link to source for an extension that does install so I can see what it's metadata.json does differently?

**Comment by mcyzyk** [comment]
Darn, it's looking like all shell extensions are coming up Unsupported on my Ubuntu Jammy:

![snapshot1](https://user-images.githubusercontent.com/7024933/189911675-7255e220-077d-483c-8225-6d97dbf96972.png)

I'm thinking I will just wait until this gets fixed, then will try again to install your extension.

Thanks!

Mark
